--
-- PostgreSQL database dump
--

\restrict GGZQMdKCnSIcQDe2eXdYMjkGn7eKJl99coGLEOftYA7WptjHnYdRZiShlsfrHcM

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: clientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clientes (
    id bigint NOT NULL,
    nombre text NOT NULL,
    telefono text,
    whatsapp text,
    email text,
    direccion text,
    ciudad text,
    observaciones text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    auth_user_id uuid,
    tipo_cliente text DEFAULT 'minorista'::text NOT NULL,
    razon_social text,
    documento text,
    notas_mayorista text,
    CONSTRAINT clientes_tipo_cliente_check CHECK ((tipo_cliente = ANY (ARRAY['minorista'::text, 'mayorista'::text])))
);


--
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estados_pedido; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_pedido (
    id bigint NOT NULL,
    nombre text NOT NULL,
    descripcion text,
    color text,
    orden integer DEFAULT 0 NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: estados_pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estados_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estados_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historial_pedidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historial_pedidos (
    id bigint NOT NULL,
    pedido_id bigint NOT NULL,
    estado_anterior_id bigint,
    estado_nuevo_id bigint,
    accion text NOT NULL,
    comentario text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: historial_pedidos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.historial_pedidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historial_pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedido_archivos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedido_archivos (
    id bigint NOT NULL,
    pedido_id bigint NOT NULL,
    pedido_detalle_id bigint,
    nombre_original text NOT NULL,
    ruta_storage text NOT NULL,
    tipo_archivo text,
    extension text,
    tamano_bytes bigint,
    descripcion text,
    tipo text DEFAULT 'imagen_cliente'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: pedido_archivos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pedido_archivos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_archivos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedido_detalles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedido_detalles (
    id bigint NOT NULL,
    pedido_id bigint NOT NULL,
    producto_id bigint NOT NULL,
    producto_nombre text NOT NULL,
    codigo_interno text,
    cantidad integer DEFAULT 1 NOT NULL,
    precio_unitario numeric(12,2) DEFAULT 0 NOT NULL,
    subtotal numeric(12,2) DEFAULT 0 NOT NULL,
    detalle text,
    creado_en timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: pedido_detalles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pedido_detalles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_detalles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedido_personalizaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedido_personalizaciones (
    id bigint NOT NULL,
    pedido_detalle_id bigint NOT NULL,
    tipo_personalizacion_id bigint,
    nombre text NOT NULL,
    descripcion text,
    valor_texto text,
    archivo_url text,
    recargo_porcentaje numeric(8,2) DEFAULT 0 NOT NULL,
    recargo_fijo numeric(12,2) DEFAULT 0 NOT NULL,
    recargo_calculado numeric(12,2) DEFAULT 0 NOT NULL,
    creado_en timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: pedido_personalizaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pedido_personalizaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_personalizaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedido_respuestas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedido_respuestas (
    id bigint NOT NULL,
    pedido_item_id bigint NOT NULL,
    pregunta_id bigint NOT NULL,
    valor_texto text,
    valor_numero numeric,
    valor_booleano boolean,
    opcion_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: pedido_respuestas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pedido_respuestas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_respuestas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedidos (
    id bigint NOT NULL,
    producto_id bigint,
    cantidad integer DEFAULT 1 NOT NULL,
    cliente_nombre text NOT NULL,
    cliente_telefono text,
    cliente_email text,
    precio_base numeric(12,2) DEFAULT 0 NOT NULL,
    recargo_personalizacion numeric(12,2) DEFAULT 0 NOT NULL,
    recargo_bolsita numeric(12,2) DEFAULT 0 NOT NULL,
    precio_total numeric(12,2) DEFAULT 0 NOT NULL,
    quiere_nombre boolean DEFAULT false NOT NULL,
    nombre_texto text,
    quiere_imagen boolean DEFAULT false NOT NULL,
    imagen_url text,
    quiere_detalle boolean DEFAULT false NOT NULL,
    detalle_diseno text,
    quiere_bolsita boolean DEFAULT false NOT NULL,
    estado text DEFAULT 'nuevo'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    numero_pedido bigint,
    subtotal numeric(12,2) DEFAULT 0,
    recargos numeric(12,2) DEFAULT 0,
    total numeric(12,2) DEFAULT 0,
    observaciones text,
    creado_en timestamp with time zone DEFAULT now(),
    actualizado_en timestamp with time zone DEFAULT now(),
    CONSTRAINT pedidos_cantidad_check CHECK ((cantidad > 0)),
    CONSTRAINT pedidos_estado_check CHECK ((estado = ANY (ARRAY['nuevo'::text, 'en_diseño'::text, 'diseño_enviado'::text, 'en_revision'::text, 'correccion'::text, 'aprobado'::text, 'produccion'::text, 'listo'::text, 'entregado'::text, 'cancelado'::text])))
);


--
-- Name: pedidos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pedidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    nombre text NOT NULL,
    email text NOT NULL,
    rol_id bigint,
    activo boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    auth_user_id uuid,
    tipo_cliente text,
    CONSTRAINT usuarios_tipo_cliente_check CHECK (((tipo_cliente IS NULL) OR (tipo_cliente = ANY (ARRAY['minorista'::text, 'mayorista'::text]))))
);


--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.clientes (id, nombre, telefono, whatsapp, email, direccion, ciudad, observaciones, created_at, updated_at, auth_user_id, tipo_cliente, razon_social, documento, notas_mayorista) FROM stdin;
1	Cliente de prueba	099111111	099111111	cliente.prueba@example.com	\N	Colonia del Sacramento	Cliente creado para probar el sistema	2026-08-10 22:51:47.017708+00	2026-08-10 22:51:47.017708+00	\N	minorista	\N	\N	\N
5	so627f14	\N	\N	so627f14@02l.arcglen.com	\N	\N	\N	2026-08-11 15:29:43.555677+00	2026-08-11 15:29:43.555677+00	23d5107c-f922-4623-8282-09876ab7bc33	minorista	\N	\N	\N
7	Cliente Prueba	\N	\N	magdaia6276ab@m5.foodlpqse.com	\N	\N	\N	2026-08-11 15:59:32.073633+00	2026-08-11 15:59:32.073633+00	75333002-11bf-4535-8f16-f13585046f30	minorista	\N	\N	\N
\.


--
-- Data for Name: estados_pedido; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.estados_pedido (id, nombre, descripcion, color, orden, activo, created_at) FROM stdin;
1	Nuevo	Pedido recibido y pendiente de revisión	\N	1	t	2026-08-10 22:23:30.650107+00
2	Revisar	Hay información que debe revisarse	\N	2	t	2026-08-10 22:23:30.650107+00
3	Diseño	Pedido en proceso de diseño	\N	3	t	2026-08-10 22:23:30.650107+00
4	Aprobación	Diseño enviado al cliente	\N	4	t	2026-08-10 22:23:30.650107+00
5	Producción	Pedido aprobado y en producción	\N	5	t	2026-08-10 22:23:30.650107+00
6	Listo	Pedido terminado	\N	6	t	2026-08-10 22:23:30.650107+00
7	Entregado	Pedido entregado al cliente	\N	7	t	2026-08-10 22:23:30.650107+00
8	Cancelado	Pedido cancelado	\N	8	t	2026-08-10 22:23:30.650107+00
\.


--
-- Data for Name: historial_pedidos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.historial_pedidos (id, pedido_id, estado_anterior_id, estado_nuevo_id, accion, comentario, created_at) FROM stdin;
1	1	\N	1	Pedido creado	Pedido de prueba creado automáticamente	2026-08-10 22:51:47.017708+00
\.


--
-- Data for Name: pedido_archivos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pedido_archivos (id, pedido_id, pedido_detalle_id, nombre_original, ruta_storage, tipo_archivo, extension, tamano_bytes, descripcion, tipo, created_at) FROM stdin;
\.


--
-- Data for Name: pedido_detalles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pedido_detalles (id, pedido_id, producto_id, producto_nombre, codigo_interno, cantidad, precio_unitario, subtotal, detalle, creado_en) FROM stdin;
3	8	18	Adorno arbolito navideño sublimable Madera Cristal	\N	1	0.00	0.00	lkjad	2026-08-13 14:32:36.339307+00
4	9	28	Azulejo 8X10 (20X25)	\N	1	0.00	0.00	k, m	2026-08-13 14:33:17.528823+00
5	10	28	Azulejo 8X10 (20X25)	\N	1	0.00	0.00	k, m	2026-08-13 15:00:23.059176+00
6	11	25	Azulejo 4X4 (10x10)	\N	1	0.00	0.00	9uuuuuu	2026-08-13 15:12:44.593416+00
7	12	33	milapollo	mila1	1	2600.00	2600.00	ggfxaaa	2026-08-13 15:58:08.326485+00
8	13	34	fideos	fideosgeniales	1	3.00	3.00	nada	2026-08-13 16:17:51.808349+00
\.


--
-- Data for Name: pedido_personalizaciones; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pedido_personalizaciones (id, pedido_detalle_id, tipo_personalizacion_id, nombre, descripcion, valor_texto, archivo_url, recargo_porcentaje, recargo_fijo, recargo_calculado, creado_en) FROM stdin;
3	5	\N	Nombre o texto	El cliente agregó un nombre, frase o texto.	ñkm	\N	2.00	0.00	0.00	2026-08-13 15:00:23.307179+00
4	5	\N	Detalle del diseño	Información proporcionada por el cliente para realizar el diseño.	k, m	\N	0.00	0.00	0.00	2026-08-13 15:00:23.611929+00
5	5	\N	Bolsita de regalo	Presentación del producto en bolsita de regalo.	Sí	\N	0.00	30.00	30.00	2026-08-13 15:00:23.947641+00
6	6	\N	Nombre o texto	El cliente agregó un nombre, frase o texto.	prueba	\N	2.00	0.00	0.00	2026-08-13 15:12:44.872426+00
7	6	\N	Detalle del diseño	Información proporcionada por el cliente para realizar el diseño.	9uuuuuu	\N	0.00	0.00	0.00	2026-08-13 15:12:45.174111+00
8	6	\N	Bolsita de regalo	Presentación del producto en bolsita de regalo.	Sí	\N	0.00	30.00	30.00	2026-08-13 15:12:45.518958+00
9	7	\N	Nombre o texto	El cliente agregó un nombre, frase o texto.	khvk	\N	2.00	0.00	52.00	2026-08-13 15:58:08.699312+00
10	7	\N	Detalle del diseño	Información proporcionada por el cliente para realizar el diseño.	ggfxaaa	\N	0.00	0.00	0.00	2026-08-13 15:58:09.006241+00
11	7	\N	Bolsita de regalo	Presentación del producto en bolsita de regalo.	Sí	\N	0.00	30.00	30.00	2026-08-13 15:58:09.312938+00
12	8	\N	Nombre o texto	El cliente agregó un nombre, frase o texto.	adri	\N	2.00	0.00	0.06	2026-08-13 16:17:52.064058+00
13	8	\N	Detalle del diseño	Información proporcionada por el cliente para realizar el diseño.	nada	\N	0.00	0.00	0.00	2026-08-13 16:17:52.302847+00
14	8	\N	Bolsita de regalo	Presentación del producto en bolsita de regalo.	Sí	\N	0.00	30.00	30.00	2026-08-13 16:17:52.553966+00
\.


--
-- Data for Name: pedido_respuestas; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pedido_respuestas (id, pedido_item_id, pregunta_id, valor_texto, valor_numero, valor_booleano, opcion_id, created_at) FROM stdin;
1	1	1	María	\N	\N	\N	2026-08-10 22:51:47.017708+00
\.


--
-- Data for Name: pedidos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pedidos (id, producto_id, cantidad, cliente_nombre, cliente_telefono, cliente_email, precio_base, recargo_personalizacion, recargo_bolsita, precio_total, quiere_nombre, nombre_texto, quiere_imagen, imagen_url, quiere_detalle, detalle_diseno, quiere_bolsita, estado, created_at, updated_at, numero_pedido, subtotal, recargos, total, observaciones, creado_en, actualizado_en) FROM stdin;
7	\N	1	pepito	1111	asdasd	0.00	0.00	0.00	0.00	f	\N	f	\N	f	\N	f	nuevo	2026-08-13 14:28:44.418738+00	2026-08-13 14:28:44.418738+00	\N	0.00	60.00	60.00	\N	2026-08-13 14:28:44.418738+00	2026-08-13 14:28:44.418738+00
8	\N	1	pepito	1111	asdasd	0.00	0.00	0.00	0.00	f	\N	f	\N	f	\N	f	nuevo	2026-08-13 14:32:36.055306+00	2026-08-13 14:32:36.055306+00	\N	0.00	60.00	60.00	\N	2026-08-13 14:32:36.055306+00	2026-08-13 14:32:36.055306+00
9	\N	1	lk	6555	oooo	0.00	0.00	0.00	0.00	f	\N	f	\N	f	\N	f	nuevo	2026-08-13 14:33:17.183193+00	2026-08-13 14:33:17.183193+00	\N	0.00	30.00	30.00	\N	2026-08-13 14:33:17.183193+00	2026-08-13 14:33:17.183193+00
10	\N	1	lk	6555	oooo	0.00	0.00	0.00	0.00	f	\N	f	\N	f	\N	f	nuevo	2026-08-13 15:00:22.779356+00	2026-08-13 15:00:22.779356+00	\N	0.00	30.00	30.00	\N	2026-08-13 15:00:22.779356+00	2026-08-13 15:00:22.779356+00
11	\N	1	prueb	00000	hhhh	0.00	0.00	0.00	0.00	f	\N	f	\N	f	\N	f	nuevo	2026-08-13 15:12:44.259381+00	2026-08-13 15:12:44.259381+00	\N	0.00	30.00	30.00	\N	2026-08-13 15:12:44.259381+00	2026-08-13 15:12:44.259381+00
12	\N	1	prueba2	65655	nbcl	0.00	0.00	0.00	0.00	f	\N	f	\N	f	\N	f	nuevo	2026-08-13 15:58:07.966918+00	2026-08-13 15:58:07.966918+00	\N	2600.00	82.00	2682.00	\N	2026-08-13 15:58:07.966918+00	2026-08-13 15:58:07.966918+00
13	\N	1	lolo	1234	asdasd	0.00	0.00	0.00	0.00	f	\N	f	\N	f	\N	f	nuevo	2026-08-13 16:17:51.583379+00	2026-08-13 16:17:51.583379+00	\N	3.00	30.06	33.06	\N	2026-08-13 16:17:51.583379+00	2026-08-13 16:17:51.583379+00
70	\N	1	x	\N	\N	0.00	0.00	0.00	0.00	f	\N	f	\N	f	\N	f	nuevo	2026-08-15 21:25:38.803202+00	2026-08-15 21:25:38.803202+00	\N	1.00	0.00	1.00	\N	2026-08-15 21:25:38.803202+00	2026-08-15 21:25:38.803202+00
6	\N	1	julio	44	adsa	0.00	0.00	0.00	0.00	f	\N	f	\N	f	\N	f	nuevo	2026-08-13 14:27:36.454184+00	2026-08-15 20:57:16.901818+00	\N	0.00	30.00	30.00	\N	2026-08-13 14:27:36.454184+00	2026-08-15 20:57:16.901818+00
14	\N	1	lolo	55555	owknd	0.00	0.00	0.00	0.00	f	\N	f	\N	f	\N	f	nuevo	2026-08-15 18:04:42.479404+00	2026-08-15 20:58:03.527673+00	\N	0.00	30.00	30.00	\N	2026-08-15 18:04:42.479404+00	2026-08-15 20:58:03.527673+00
15	\N	1	fulano	2345	alkmsdokinas	0.00	0.00	0.00	0.00	f	\N	f	\N	f	\N	f	nuevo	2026-08-15 18:08:22.946456+00	2026-08-15 20:58:03.995819+00	\N	3.00	30.06	33.06	\N	2026-08-15 18:08:22.946456+00	2026-08-15 20:58:03.995819+00
72	\N	1	x	\N	\N	0.00	0.00	0.00	0.00	f	\N	f	\N	f	\N	f	nuevo	2026-08-15 21:35:55.321469+00	2026-08-15 21:35:55.321469+00	\N	1.00	0.00	1.00	\N	2026-08-15 21:35:55.321469+00	2026-08-15 21:35:55.321469+00
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios (id, nombre, email, rol_id, activo, created_at, updated_at, auth_user_id, tipo_cliente) FROM stdin;
1	AlexisAdmin	alexisalfaro9898@gmail.com	1	t	2026-08-11 21:23:32.318231+00	2026-08-11 21:23:32.318231+00	52b3094b-44b7-4133-8c80-a3f2b4f02b30	\N
\.


--
-- Name: clientes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.clientes_id_seq', 14, true);


--
-- Name: estados_pedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.estados_pedido_id_seq', 8, true);


--
-- Name: historial_pedidos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.historial_pedidos_id_seq', 8, true);


--
-- Name: pedido_archivos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pedido_archivos_id_seq', 4, true);


--
-- Name: pedido_detalles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pedido_detalles_id_seq', 11, true);


--
-- Name: pedido_personalizaciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pedido_personalizaciones_id_seq', 22, true);


--
-- Name: pedido_respuestas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pedido_respuestas_id_seq', 10, true);


--
-- Name: pedidos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pedidos_id_seq', 76, true);


--
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 3, true);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- Name: estados_pedido estados_pedido_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_pedido
    ADD CONSTRAINT estados_pedido_nombre_key UNIQUE (nombre);


--
-- Name: estados_pedido estados_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_pedido
    ADD CONSTRAINT estados_pedido_pkey PRIMARY KEY (id);


--
-- Name: historial_pedidos historial_pedidos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_pedidos
    ADD CONSTRAINT historial_pedidos_pkey PRIMARY KEY (id);


--
-- Name: pedido_archivos pedido_archivos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_archivos
    ADD CONSTRAINT pedido_archivos_pkey PRIMARY KEY (id);


--
-- Name: pedido_detalles pedido_detalles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_detalles
    ADD CONSTRAINT pedido_detalles_pkey PRIMARY KEY (id);


--
-- Name: pedido_personalizaciones pedido_personalizaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_personalizaciones
    ADD CONSTRAINT pedido_personalizaciones_pkey PRIMARY KEY (id);


--
-- Name: pedido_respuestas pedido_respuestas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_respuestas
    ADD CONSTRAINT pedido_respuestas_pkey PRIMARY KEY (id);


--
-- Name: pedidos pedidos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_pkey PRIMARY KEY (id);


--
-- Name: usuarios usuarios_auth_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_auth_user_id_key UNIQUE (auth_user_id);


--
-- Name: usuarios usuarios_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_email_key UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: clientes_auth_user_id_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX clientes_auth_user_id_unique ON public.clientes USING btree (auth_user_id) WHERE (auth_user_id IS NOT NULL);


--
-- Name: idx_archivos_pedido; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_archivos_pedido ON public.pedido_archivos USING btree (pedido_id);


--
-- Name: idx_clientes_auth_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_clientes_auth_user_id ON public.clientes USING btree (auth_user_id);


--
-- Name: idx_historial_pedido; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_historial_pedido ON public.historial_pedidos USING btree (pedido_id);


--
-- Name: idx_pedido_archivos_pedido; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pedido_archivos_pedido ON public.pedido_archivos USING btree (pedido_id);


--
-- Name: idx_pedido_detalles_pedido; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pedido_detalles_pedido ON public.pedido_detalles USING btree (pedido_id);


--
-- Name: idx_pedido_detalles_producto; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pedido_detalles_producto ON public.pedido_detalles USING btree (producto_id);


--
-- Name: idx_pedido_personalizaciones_detalle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pedido_personalizaciones_detalle ON public.pedido_personalizaciones USING btree (pedido_detalle_id);


--
-- Name: idx_pedido_respuestas_item; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pedido_respuestas_item ON public.pedido_respuestas USING btree (pedido_item_id);


--
-- Name: idx_pedidos_creado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pedidos_creado ON public.pedidos USING btree (creado_en DESC);


--
-- Name: idx_pedidos_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pedidos_estado ON public.pedidos USING btree (estado);


--
-- Name: pedidos_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pedidos_created_at_idx ON public.pedidos USING btree (created_at DESC);


--
-- Name: pedidos_estado_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pedidos_estado_idx ON public.pedidos USING btree (estado);


--
-- Name: pedidos_producto_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pedidos_producto_id_idx ON public.pedidos USING btree (producto_id);


--
-- Name: pedidos pedidos_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER pedidos_updated_at BEFORE UPDATE ON public.pedidos FOR EACH ROW EXECUTE FUNCTION public.actualizar_updated_at();


--
-- Name: pedidos trigger_actualizar_pedido_fecha; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_actualizar_pedido_fecha BEFORE UPDATE ON public.pedidos FOR EACH ROW EXECUTE FUNCTION public.actualizar_pedido_fecha();


--
-- Name: pedidos trigger_historial_pedido; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_historial_pedido AFTER UPDATE ON public.pedidos FOR EACH ROW EXECUTE FUNCTION public.registrar_historial_pedido();


--
-- Name: historial_pedidos historial_pedidos_estado_anterior_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_pedidos
    ADD CONSTRAINT historial_pedidos_estado_anterior_id_fkey FOREIGN KEY (estado_anterior_id) REFERENCES public.estados_pedido(id) ON DELETE SET NULL;


--
-- Name: historial_pedidos historial_pedidos_estado_nuevo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_pedidos
    ADD CONSTRAINT historial_pedidos_estado_nuevo_id_fkey FOREIGN KEY (estado_nuevo_id) REFERENCES public.estados_pedido(id) ON DELETE SET NULL;


--
-- Name: pedido_archivos pedido_archivos_pedido_detalle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_archivos
    ADD CONSTRAINT pedido_archivos_pedido_detalle_id_fkey FOREIGN KEY (pedido_detalle_id) REFERENCES public.pedido_detalles(id);


--
-- Name: pedido_detalles pedido_detalles_pedido_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_detalles
    ADD CONSTRAINT pedido_detalles_pedido_id_fkey FOREIGN KEY (pedido_id) REFERENCES public.pedidos(id) ON DELETE CASCADE;


--
-- Name: pedido_detalles pedido_detalles_producto_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_detalles
    ADD CONSTRAINT pedido_detalles_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.productos(id) ON DELETE RESTRICT;


--
-- Name: pedido_personalizaciones pedido_personalizaciones_pedido_detalle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_personalizaciones
    ADD CONSTRAINT pedido_personalizaciones_pedido_detalle_id_fkey FOREIGN KEY (pedido_detalle_id) REFERENCES public.pedido_detalles(id) ON DELETE CASCADE;


--
-- Name: pedido_personalizaciones pedido_personalizaciones_tipo_personalizacion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_personalizaciones
    ADD CONSTRAINT pedido_personalizaciones_tipo_personalizacion_id_fkey FOREIGN KEY (tipo_personalizacion_id) REFERENCES public.tipos_personalizacion(id) ON DELETE SET NULL;


--
-- Name: pedido_respuestas pedido_respuestas_opcion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_respuestas
    ADD CONSTRAINT pedido_respuestas_opcion_id_fkey FOREIGN KEY (opcion_id) REFERENCES public.pregunta_opciones(id) ON DELETE RESTRICT;


--
-- Name: pedido_respuestas pedido_respuestas_pedido_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_respuestas
    ADD CONSTRAINT pedido_respuestas_pedido_item_id_fkey FOREIGN KEY (pedido_item_id) REFERENCES public.pedido_items(id) ON DELETE CASCADE;


--
-- Name: pedido_respuestas pedido_respuestas_pregunta_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_respuestas
    ADD CONSTRAINT pedido_respuestas_pregunta_id_fkey FOREIGN KEY (pregunta_id) REFERENCES public.preguntas(id) ON DELETE RESTRICT;


--
-- Name: pedidos pedidos_producto_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.productos(id) ON DELETE RESTRICT;


--
-- Name: usuarios usuarios_rol_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES public.roles(id) ON DELETE RESTRICT;


--
-- Name: pedidos Pedidos actualizacion publica; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Pedidos actualizacion publica" ON public.pedidos FOR UPDATE TO authenticated, anon USING (true) WITH CHECK (true);


--
-- Name: pedidos Pedidos insercion publica; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Pedidos insercion publica" ON public.pedidos FOR INSERT TO authenticated, anon WITH CHECK (true);


--
-- Name: pedidos Pedidos lectura publica; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Pedidos lectura publica" ON public.pedidos FOR SELECT TO authenticated, anon USING (true);


--
-- Name: pedido_detalles Permitir consultar pedido_detalles; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Permitir consultar pedido_detalles" ON public.pedido_detalles FOR SELECT USING (true);


--
-- Name: pedido_archivos Permitir crear pedido_archivos; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Permitir crear pedido_archivos" ON public.pedido_archivos FOR INSERT TO authenticated, anon WITH CHECK (true);


--
-- Name: pedido_personalizaciones Permitir crear pedido_personalizaciones; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Permitir crear pedido_personalizaciones" ON public.pedido_personalizaciones FOR INSERT TO authenticated, anon WITH CHECK (true);


--
-- Name: pedido_detalles Permitir insertar pedido_detalles; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Permitir insertar pedido_detalles" ON public.pedido_detalles FOR INSERT WITH CHECK (true);


--
-- Name: clientes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;

--
-- Name: clientes clientes_insert_propio; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY clientes_insert_propio ON public.clientes FOR INSERT TO authenticated WITH CHECK ((auth_user_id = auth.uid()));


--
-- Name: clientes clientes_select_propio; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY clientes_select_propio ON public.clientes FOR SELECT TO authenticated USING ((auth_user_id = auth.uid()));


--
-- Name: clientes clientes_update_propio; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY clientes_update_propio ON public.clientes FOR UPDATE TO authenticated USING ((auth_user_id = auth.uid())) WITH CHECK ((auth_user_id = auth.uid()));


--
-- Name: estados_pedido; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.estados_pedido ENABLE ROW LEVEL SECURITY;

--
-- Name: historial_pedidos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.historial_pedidos ENABLE ROW LEVEL SECURITY;

--
-- Name: pedido_archivos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pedido_archivos ENABLE ROW LEVEL SECURITY;

--
-- Name: pedido_detalles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pedido_detalles ENABLE ROW LEVEL SECURITY;

--
-- Name: pedido_personalizaciones; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pedido_personalizaciones ENABLE ROW LEVEL SECURITY;

--
-- Name: pedido_respuestas; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pedido_respuestas ENABLE ROW LEVEL SECURITY;

--
-- Name: pedidos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;

--
-- Name: usuarios; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;

--
-- Name: usuarios usuarios_permitir_usuario_autenticado; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY usuarios_permitir_usuario_autenticado ON public.usuarios FOR SELECT TO authenticated USING (true);


--
-- PostgreSQL database dump complete
--

\unrestrict GGZQMdKCnSIcQDe2eXdYMjkGn7eKJl99coGLEOftYA7WptjHnYdRZiShlsfrHcM

