-- ============================================================
-- MIGRACIÓN v28: Chat con el administrador + notificaciones
-- + suscripciones de notificaciones push (PWA).
--
-- Nuevas tablas:
--   conversaciones       -> una por cliente (chat cliente <-> admin)
--   mensajes             -> los mensajes de cada conversación
--   notificaciones       -> avisos in-app con contexto de pedido
--   push_suscripciones   -> suscripciones Web Push por usuario
--
-- RLS:
--   * El cliente autenticado solo ve/edita su propia conversación y
--     sus notificaciones.
--   * El personal (es_personal()) ve/edita todo.
--   * Las suscripciones push son por auth.uid() (owner).
--
-- Realtime: se publican mensajes y notificaciones (supabase_realtime).
-- ============================================================

BEGIN;

-- ============================================================
-- 1) CONVERSACIONES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.conversaciones (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id    bigint NOT NULL REFERENCES public.clientes(id) ON DELETE CASCADE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  UNIQUE (cliente_id)
);

ALTER TABLE public.conversaciones ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.conversaciones ADD COLUMN IF NOT EXISTS ultimo_mensaje_at timestamptz;

CREATE INDEX IF NOT EXISTS idx_conversaciones_cliente ON public.conversaciones(cliente_id);

-- ============================================================
-- 2) MENSAJES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.mensajes (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversacion_id  bigint NOT NULL REFERENCES public.conversaciones(id) ON DELETE CASCADE,
  remitente_tipo   text NOT NULL CHECK (remitente_tipo IN ('cliente','admin','sistema')),
  texto            text NOT NULL DEFAULT '',
  leido            boolean NOT NULL DEFAULT false,
  creado_en        timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.mensajes ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_mensajes_conversacion ON public.mensajes(conversacion_id, id);

-- ============================================================
-- 3) NOTIFICACIONES (in-app, con contexto de pedido)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.notificaciones (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  para_tipo      text NOT NULL CHECK (para_tipo IN ('cliente','admin')),
  -- destinatario del tipo 'cliente' (null si es admin)
  cliente_id     bigint REFERENCES public.clientes(id) ON DELETE CASCADE,
  tipo           text NOT NULL DEFAULT 'generico',
  titulo         text NOT NULL DEFAULT '',
  cuerpo         text NOT NULL DEFAULT '',
  ref_pedido_id  bigint REFERENCES public.pedidos(id) ON DELETE SET NULL,
  leida          boolean NOT NULL DEFAULT false,
  creado_en      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.notificaciones ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_notif_cliente ON public.notificaciones(cliente_id, leida, id);
CREATE INDEX IF NOT EXISTS idx_notif_admin ON public.notificaciones(para_tipo, leida, id);

-- ============================================================
-- 4) SUSCRIPCIONES PUSH (Web Push / PWA)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.push_suscripciones (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid NOT NULL, -- auth.uid()
  endpoint   text NOT NULL,
  p256dh     text NOT NULL,
  auth       text NOT NULL,
  creado_en  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (endpoint)
);

ALTER TABLE public.push_suscripciones ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_push_user ON public.push_suscripciones(user_id);

-- ============================================================
-- FUNCIÓN AYUDANTE: id de cliente autenticado (para RLS)
-- ============================================================
CREATE OR REPLACE FUNCTION public.cliente_autenticado_id()
RETURNS bigint
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = 'public'
AS $$
  SELECT id FROM public.clientes
  WHERE auth_user_id = auth.uid()
  LIMIT 1;
$$;

-- ============================================================
-- RLS: CONVERSACIONES
-- ============================================================
DROP POLICY IF EXISTS conv_select ON public.conversaciones;
CREATE POLICY conv_select ON public.conversaciones
  FOR SELECT TO authenticated
  USING (es_personal() OR cliente_id = public.cliente_autenticado_id());

DROP POLICY IF EXISTS conv_insert ON public.conversaciones;
CREATE POLICY conv_insert ON public.conversaciones
  FOR INSERT TO authenticated
  WITH CHECK (cliente_id = public.cliente_autenticado_id() OR es_personal());

DROP POLICY IF EXISTS conv_update ON public.conversaciones;
CREATE POLICY conv_update ON public.conversaciones
  FOR UPDATE TO authenticated
  USING (es_personal() OR cliente_id = public.cliente_autenticado_id());

-- ============================================================
-- RLS: MENSAJES
-- ============================================================
DROP POLICY IF EXISTS msg_select ON public.mensajes;
CREATE POLICY msg_select ON public.mensajes
  FOR SELECT TO authenticated
  USING (
    es_personal()
    OR conversacion_id IN (
      SELECT c.id FROM public.conversaciones c
      WHERE c.cliente_id = public.cliente_autenticado_id()
    )
  );

DROP POLICY IF EXISTS msg_insert ON public.mensajes;
CREATE POLICY msg_insert ON public.mensajes
  FOR INSERT TO authenticated
  WITH CHECK (
    remitente_tipo IN ('cliente','admin')
    AND (
      (es_personal() AND remitente_tipo = 'admin')
      OR
      (NOT es_personal() AND remitente_tipo = 'cliente'
       AND conversacion_id IN (
         SELECT c.id FROM public.conversaciones c
         WHERE c.cliente_id = public.cliente_autenticado_id()
       ))
    )
  );

DROP POLICY IF EXISTS msg_update ON public.mensajes;
CREATE POLICY msg_update ON public.mensajes
  FOR UPDATE TO authenticated
  USING (
    es_personal()
    OR conversacion_id IN (
      SELECT c.id FROM public.conversaciones c
      WHERE c.cliente_id = public.cliente_autenticado_id()
    )
  );

-- ============================================================
-- RLS: NOTIFICACIONES
-- ============================================================
DROP POLICY IF EXISTS notif_select ON public.notificaciones;
CREATE POLICY notif_select ON public.notificaciones
  FOR SELECT TO authenticated
  USING (
    (para_tipo = 'admin' AND es_personal())
    OR
    (para_tipo = 'cliente' AND cliente_id = public.cliente_autenticado_id())
  );

DROP POLICY IF EXISTS notif_insert ON public.notificaciones;
CREATE POLICY notif_insert ON public.notificaciones
  FOR INSERT TO authenticated
  WITH CHECK (es_personal() OR cliente_id = public.cliente_autenticado_id());

DROP POLICY IF EXISTS notif_update ON public.notificaciones;
CREATE POLICY notif_update ON public.notificaciones
  FOR UPDATE TO authenticated
  USING (
    (para_tipo = 'admin' AND es_personal())
    OR
    (para_tipo = 'cliente' AND cliente_id = public.cliente_autenticado_id())
  );

-- ============================================================
-- RLS: PUSH SUSCRIPCIONES (solo el owner / personal)
-- ============================================================
DROP POLICY IF EXISTS push_owner_select ON public.push_suscripciones;
CREATE POLICY push_owner_select ON public.push_suscripciones
  FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR es_personal());

DROP POLICY IF EXISTS push_owner_insert ON public.push_suscripciones;
CREATE POLICY push_owner_insert ON public.push_suscripciones
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid() OR es_personal());

DROP POLICY IF EXISTS push_owner_delete ON public.push_suscripciones;
CREATE POLICY push_owner_delete ON public.push_suscripciones
  FOR DELETE TO authenticated
  USING (user_id = auth.uid() OR es_personal());

-- ============================================================
-- CONCEDE USO DE SECUENCIAS A ROLES (si falla, se ignora)
-- ============================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.conversaciones, public.mensajes, public.notificaciones TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.push_suscripciones TO authenticated;

COMMIT;
