-- ============================================================
-- MIGRACIÓN v20: Mockups de catálogo
-- ============================================================
-- `imagen_original`: URL de la foto en blanco del proveedor
--   (se guarda al generar el mockup, para poder revertir).
-- `imagen_mockup`: URL en nuestro storage del producto con el
--   diseño estampado. La vitrina la prefiere sobre la original.
-- `disenos_catalogo`: galería de diseños predefinidos por
--   segmento de cliente, para generar mockups variados.
-- `diseno_asignacion`: qué diseño se usó en cada mockup.
-- Todo idempotente (IF NOT EXISTS / IF EXISTS).

-- 1. Columnas nuevas en productos
ALTER TABLE public.productos
  ADD COLUMN IF NOT EXISTS imagen_original TEXT,
  ADD COLUMN IF NOT EXISTS imagen_mockup TEXT;

-- 2. Galería de diseños de catálogo
CREATE TABLE IF NOT EXISTS public.disenos_catalogo (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        TEXT NOT NULL,
  segmento      TEXT NOT NULL DEFAULT 'general',
  archivo_url   TEXT NOT NULL,
  activo        BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. Asignación diseño -> producto
CREATE TABLE IF NOT EXISTS public.diseno_asignacion (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id   BIGINT NOT NULL REFERENCES public.productos(id) ON DELETE CASCADE,
  diseno_id     BIGINT NOT NULL REFERENCES public.disenos_catalogo(id) ON DELETE CASCADE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (producto_id)
);

-- 4. RLS: solo personal autenticado gestiona diseños/asignaciones
ALTER TABLE public.disenos_catalogo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diseno_asignacion ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'disenos_catalogo'
  ) THEN
    CREATE POLICY "disenos_catalogo_personal"
      ON public.disenos_catalogo
      FOR ALL TO authenticated
      USING (true)
      WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'diseno_asignacion'
  ) THEN
    CREATE POLICY "diseno_asignacion_personal"
      ON public.diseno_asignacion
      FOR ALL TO authenticated
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;